name: Build APK (Docker Ubuntu 20.04)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04

    steps:
      - name: Install system dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            openjdk-17-jdk git zip unzip colordiff ccache \
            python3-pip python3-setuptools python3-virtualenv \
            libffi-dev libssl-dev build-essential patch autoconf \
            libtool pkg-config zlib1g-dev libncurses5-dev libltdl-dev

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Buildozer and Cython
        run: |
          pip3 install --upgrade pip
          pip3 install "cython<3.0.0" buildozer

      - name: Build APK
        run: |
          export CFLAGS="-Wno-error=implicit-function-declaration"
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: leaf-apk
          path: bin/*.apk
